# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pusat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=200)),
                ('tujuan', models.CharField(max_length=100)),
                ('jumlah', models.FloatField()),
                ('proposal', models.FileField(upload_to='')),
                ('pusat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rab.Pusat')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nama_sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_transfer', models.DateTimeField(auto_now_add=True)),
                ('uraian', models.CharField(max_length=100)),
                ('jumlah', models.FloatField()),
                ('pusat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rab.Pusat')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rab.Sub')),
            ],
        ),
        migrations.CreateModel(
            name='ValRab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.CharField(max_length=40)),
                ('harga', models.FloatField()),
                ('bukti_item', models.ImageField(upload_to='')),
                ('bukti_transfer', models.ImageField(upload_to='')),
                ('rab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rab.Rab')),
            ],
        ),
        migrations.CreateModel(
            name='ValTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.CharField(max_length=40)),
                ('harga', models.FloatField()),
                ('bukti_item', models.ImageField(upload_to='')),
                ('bukti_transfer', models.ImageField(upload_to='')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rab.Transfer')),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='pusat',
            field=models.ManyToManyField(through='rab.Transfer', to='rab.Pusat'),
        ),
        migrations.AddField(
            model_name='rab',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rab.Sub'),
        ),
    ]
