# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0003_auto_20200512_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valtransfer',
            name='bukti_item',
            field=models.ImageField(upload_to='C:/Users/user/'),
        ),
        migrations.AlterField(
            model_name='valtransfer',
            name='bukti_transfer',
            field=models.ImageField(upload_to='C:/Users/user/'),
        ),
    ]
