# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0005_auto_20200513_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valtransfer',
            name='bukti_item',
            field=models.ImageField(upload_to='gambar/'),
        ),
        migrations.AlterField(
            model_name='valtransfer',
            name='bukti_transfer',
            field=models.ImageField(upload_to='gambar/'),
        ),
    ]
