# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0006_auto_20200513_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rab',
            name='proposal',
            field=models.FileField(default='default.pdf', upload_to='file'),
        ),
        migrations.AlterField(
            model_name='valrab',
            name='bukti_item',
            field=models.ImageField(default='default.jpg', upload_to='gambar/bukti_item'),
        ),
        migrations.AlterField(
            model_name='valrab',
            name='bukti_transfer',
            field=models.ImageField(default='default.jpg', upload_to='gambar/bukti_transfer'),
        ),
        migrations.AlterField(
            model_name='valtransfer',
            name='bukti_item',
            field=models.ImageField(default='default.jpg', upload_to='gambar/bukti_item'),
        ),
        migrations.AlterField(
            model_name='valtransfer',
            name='bukti_transfer',
            field=models.ImageField(default='default.jpg', upload_to='gambar/bukti_transfer'),
        ),
    ]
