# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0007_auto_20200513_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='rab',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
