# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0008_rab_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='pengeluaran',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='jumlah',
            field=models.FloatField(default=0),
        ),
    ]
