# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rab', '0009_auto_20200514_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='valtransfer',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
