# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='boby',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='nama@web.com', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='waktu_posting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
